name = "LoRDeckCodes"
uuid = "078e6c93-a565-420a-af46-e2c4e3180690"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[deps]
CodecBase = "6c391c72-fb7b-5838-ba82-7cfb1bcfecbf"

[extras]
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Jive"]

[compat]
julia = "1"
